"""ATHENA canonical domain model (ATHENA-002 §4) — frozen contracts between all modules.

Pure layer: no I/O, no network, no clock reads. Changing any object here is a
reviewed change; removing/renaming a field requires a blueprint amendment (ADR).
"""

from athena.domain.context import ContextDelta, PipelineContext
from athena.domain.decision import (
    CapitalState,
    Decision,
    DecisionJournalEntry,
    DecisionTrace,
    GateResult,
    Portfolio,
    Position,
    RiskEvaluation,
    TraceStage,
    TradeOutcome,
    TradePlan,
)
from athena.domain.enums import (
    CumulativeNature,
    DecisionType,
    Direction,
    EvidenceCategory,
    FilingAuditStatus,
    HealthStatus,
    PeriodNature,
    PublicationPrecision,
    QualityGate,
    RunStatus,
    RunTrigger,
    SessionType,
    StatementScope,
    Timeframe,
    UserAction,
)
from athena.domain.evidence import (
    ConfidenceAssessment,
    Evidence,
    ExplainabilityReport,
    Score,
    Signal,
)
from athena.domain.fundamentals import (
    MAX_RAW_DOCUMENT_SIZE_BYTES,
    FilingDocument,
    FundamentalFiling,
    IssuerRecord,
    SecurityIdentity,
)
from athena.domain.health import HealthCheck, SystemHealthReport
from athena.domain.interfaces import (
    InstitutionalFlowProvider,
    IntelligenceModule,
    MarketDataProvider,
    ProviderCapabilities,
    ProviderHealth,
)
from athena.domain.market import (
    CalendarContext,
    CalendarEvent,
    Candle,
    CorporateAction,
    InstitutionalFlowSession,
    Instrument,
    MarketHealthScore,
    MarketSnapshot,
    Quote,
    RegimeAssessment,
    SectorHealthScore,
    SectorSnapshot,
    Universe,
    UniverseMember,
)
from athena.domain.run import ConfigurationSnapshot, RunRecord

__all__ = [
    "MAX_RAW_DOCUMENT_SIZE_BYTES",
    "CalendarContext",
    "CalendarEvent",
    "Candle",
    "CapitalState",
    "ConfidenceAssessment",
    "ConfigurationSnapshot",
    "ContextDelta",
    "CorporateAction",
    "CumulativeNature",
    "Decision",
    "DecisionJournalEntry",
    "DecisionTrace",
    "DecisionType",
    "Direction",
    "Evidence",
    "EvidenceCategory",
    "ExplainabilityReport",
    "FilingAuditStatus",
    "FilingDocument",
    "FundamentalFiling",
    "GateResult",
    "HealthCheck",
    "HealthStatus",
    "InstitutionalFlowProvider",
    "InstitutionalFlowSession",
    "Instrument",
    "IntelligenceModule",
    "IssuerRecord",
    "MarketDataProvider",
    "MarketHealthScore",
    "MarketSnapshot",
    "PeriodNature",
    "PipelineContext",
    "Portfolio",
    "Position",
    "ProviderCapabilities",
    "ProviderHealth",
    "PublicationPrecision",
    "QualityGate",
    "Quote",
    "RegimeAssessment",
    "RiskEvaluation",
    "RunRecord",
    "RunStatus",
    "RunTrigger",
    "Score",
    "SectorHealthScore",
    "SectorSnapshot",
    "SecurityIdentity",
    "SessionType",
    "Signal",
    "StatementScope",
    "SystemHealthReport",
    "Timeframe",
    "TraceStage",
    "TradeOutcome",
    "TradePlan",
    "Universe",
    "UniverseMember",
    "UserAction",
]
